-- Migration: convert every timestamp(3) column to timestamptz(3) (UTC).
-- Generated by scripts/generate-tz-migration.ts
-- Backfill rule: existing values are interpreted as UTC (the historical
-- convention — every prior writer used .toISOString() / toISOString UTC).

BEGIN;

ALTER TABLE "audit_log"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "category"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "expired_festival_manual_book"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz;

ALTER TABLE "expired_festival_result"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz;

ALTER TABLE "festival"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "endDate" TYPE TIMESTAMPTZ(3) USING ("endDate"::text)::timestamptz,
  ALTER COLUMN "expiredAt" TYPE TIMESTAMPTZ(3) USING ("expiredAt"::text)::timestamptz,
  ALTER COLUMN "expiresAt" TYPE TIMESTAMPTZ(3) USING ("expiresAt"::text)::timestamptz,
  ALTER COLUMN "participantCreationDeadline" TYPE TIMESTAMPTZ(3) USING ("participantCreationDeadline"::text)::timestamptz,
  ALTER COLUMN "programmeAssignmentDeadline" TYPE TIMESTAMPTZ(3) USING ("programmeAssignmentDeadline"::text)::timestamptz,
  ALTER COLUMN "startDate" TYPE TIMESTAMPTZ(3) USING ("startDate"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "festival_category_preference"
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "festival_export"
  ALTER COLUMN "completedAt" TYPE TIMESTAMPTZ(3) USING ("completedAt"::text)::timestamptz,
  ALTER COLUMN "expiresAt" TYPE TIMESTAMPTZ(3) USING ("expiresAt"::text)::timestamptz,
  ALTER COLUMN "queuedAt" TYPE TIMESTAMPTZ(3) USING ("queuedAt"::text)::timestamptz;

ALTER TABLE "festival_lifecycle_event"
  ALTER COLUMN "occurredAt" TYPE TIMESTAMPTZ(3) USING ("occurredAt"::text)::timestamptz;

ALTER TABLE "festival_media_image"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "festival_member"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "festival_news"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "publishedAt" TYPE TIMESTAMPTZ(3) USING ("publishedAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "festival_poster_template"
  ALTER COLUMN "created_at" TYPE TIMESTAMPTZ(3) USING ("created_at"::text)::timestamptz,
  ALTER COLUMN "updated_at" TYPE TIMESTAMPTZ(3) USING ("updated_at"::text)::timestamptz;

ALTER TABLE "festival_scoring_award_rule"
  ALTER COLUMN "created_at" TYPE TIMESTAMPTZ(3) USING ("created_at"::text)::timestamptz,
  ALTER COLUMN "updated_at" TYPE TIMESTAMPTZ(3) USING ("updated_at"::text)::timestamptz;

ALTER TABLE "festival_scoring_policy"
  ALTER COLUMN "created_at" TYPE TIMESTAMPTZ(3) USING ("created_at"::text)::timestamptz,
  ALTER COLUMN "updated_at" TYPE TIMESTAMPTZ(3) USING ("updated_at"::text)::timestamptz;

ALTER TABLE "group"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "institution"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "judge"
  ALTER COLUMN "created_at" TYPE TIMESTAMPTZ(3) USING ("created_at"::text)::timestamptz,
  ALTER COLUMN "updated_at" TYPE TIMESTAMPTZ(3) USING ("updated_at"::text)::timestamptz;

ALTER TABLE "judge_stage_assignment"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz;

ALTER TABLE "judgement_config"
  ALTER COLUMN "created_at" TYPE TIMESTAMPTZ(3) USING ("created_at"::text)::timestamptz,
  ALTER COLUMN "ended_at" TYPE TIMESTAMPTZ(3) USING ("ended_at"::text)::timestamptz,
  ALTER COLUMN "started_at" TYPE TIMESTAMPTZ(3) USING ("started_at"::text)::timestamptz,
  ALTER COLUMN "updated_at" TYPE TIMESTAMPTZ(3) USING ("updated_at"::text)::timestamptz;

ALTER TABLE "judgement_config_judge"
  ALTER COLUMN "created_at" TYPE TIMESTAMPTZ(3) USING ("created_at"::text)::timestamptz;

ALTER TABLE "judgement_score"
  ALTER COLUMN "submitted_at" TYPE TIMESTAMPTZ(3) USING ("submitted_at"::text)::timestamptz,
  ALTER COLUMN "updated_at" TYPE TIMESTAMPTZ(3) USING ("updated_at"::text)::timestamptz;

ALTER TABLE "magic_link_token"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "expiresAt" TYPE TIMESTAMPTZ(3) USING ("expiresAt"::text)::timestamptz,
  ALTER COLUMN "usedAt" TYPE TIMESTAMPTZ(3) USING ("usedAt"::text)::timestamptz;

ALTER TABLE "participant"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "dateOfBirth" TYPE TIMESTAMPTZ(3) USING ("dateOfBirth"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "participant_otp"
  ALTER COLUMN "consumedAt" TYPE TIMESTAMPTZ(3) USING ("consumedAt"::text)::timestamptz,
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "expiresAt" TYPE TIMESTAMPTZ(3) USING ("expiresAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "participant_session"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "expiresAt" TYPE TIMESTAMPTZ(3) USING ("expiresAt"::text)::timestamptz,
  ALTER COLUMN "revokedAt" TYPE TIMESTAMPTZ(3) USING ("revokedAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "payment"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz,
  ALTER COLUMN "validUntil" TYPE TIMESTAMPTZ(3) USING ("validUntil"::text)::timestamptz;

ALTER TABLE "pending_invitation"
  ALTER COLUMN "acceptedAt" TYPE TIMESTAMPTZ(3) USING ("acceptedAt"::text)::timestamptz,
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "expiresAt" TYPE TIMESTAMPTZ(3) USING ("expiresAt"::text)::timestamptz;

ALTER TABLE "programme"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "publishedAt" TYPE TIMESTAMPTZ(3) USING ("publishedAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "programme_assignment"
  ALTER COLUMN "assignedAt" TYPE TIMESTAMPTZ(3) USING ("assignedAt"::text)::timestamptz,
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "programme_code_letter"
  ALTER COLUMN "absent_at" TYPE TIMESTAMPTZ(3) USING ("absent_at"::text)::timestamptz,
  ALTER COLUMN "issuedAt" TYPE TIMESTAMPTZ(3) USING ("issuedAt"::text)::timestamptz;

ALTER TABLE "programme_code_letter_recipient"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz;

ALTER TABLE "programme_notification"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz;

ALTER TABLE "programme_reported_participant"
  ALTER COLUMN "reportedAt" TYPE TIMESTAMPTZ(3) USING ("reportedAt"::text)::timestamptz;

ALTER TABLE "programme_reporting_session"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "endedAt" TYPE TIMESTAMPTZ(3) USING ("endedAt"::text)::timestamptz,
  ALTER COLUMN "startedAt" TYPE TIMESTAMPTZ(3) USING ("startedAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz,
  ALTER COLUMN "windowEndsAt" TYPE TIMESTAMPTZ(3) USING ("windowEndsAt"::text)::timestamptz;

ALTER TABLE "programme_team_lead"
  ALTER COLUMN "appointedAt" TYPE TIMESTAMPTZ(3) USING ("appointedAt"::text)::timestamptz,
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "result"
  ALTER COLUMN "announcedAt" TYPE TIMESTAMPTZ(3) USING ("announcedAt"::text)::timestamptz,
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "schedule_entry"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "endTime" TYPE TIMESTAMPTZ(3) USING ("endTime"::text)::timestamptz,
  ALTER COLUMN "startTime" TYPE TIMESTAMPTZ(3) USING ("startTime"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "stage"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "stage_manager_assignment"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz;

ALTER TABLE "stage_portal_credential"
  ALTER COLUMN "created_at" TYPE TIMESTAMPTZ(3) USING ("created_at"::text)::timestamptz,
  ALTER COLUMN "locked_until" TYPE TIMESTAMPTZ(3) USING ("locked_until"::text)::timestamptz,
  ALTER COLUMN "updated_at" TYPE TIMESTAMPTZ(3) USING ("updated_at"::text)::timestamptz;

ALTER TABLE "stage_portal_session"
  ALTER COLUMN "created_at" TYPE TIMESTAMPTZ(3) USING ("created_at"::text)::timestamptz,
  ALTER COLUMN "expires_at" TYPE TIMESTAMPTZ(3) USING ("expires_at"::text)::timestamptz,
  ALTER COLUMN "revoked_at" TYPE TIMESTAMPTZ(3) USING ("revoked_at"::text)::timestamptz,
  ALTER COLUMN "updated_at" TYPE TIMESTAMPTZ(3) USING ("updated_at"::text)::timestamptz;

ALTER TABLE "system_config"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "user"
  ALTER COLUMN "createdAt" TYPE TIMESTAMPTZ(3) USING ("createdAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "user_login_event"
  ALTER COLUMN "loggedAt" TYPE TIMESTAMPTZ(3) USING ("loggedAt"::text)::timestamptz;

ALTER TABLE "user_purchase_summary"
  ALTER COLUMN "lastPurchaseAt" TYPE TIMESTAMPTZ(3) USING ("lastPurchaseAt"::text)::timestamptz,
  ALTER COLUMN "updatedAt" TYPE TIMESTAMPTZ(3) USING ("updatedAt"::text)::timestamptz;

ALTER TABLE "audit_log"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "category"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "expired_festival_manual_book"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "expired_festival_result"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "festival"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "festival_category_preference"
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "festival_export"
  ALTER COLUMN "queuedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "festival_lifecycle_event"
  ALTER COLUMN "occurredAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "festival_media_image"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "festival_member"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "festival_news"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "festival_poster_template"
  ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "festival_scoring_award_rule"
  ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "festival_scoring_policy"
  ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "group"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "institution"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "judge"
  ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "judge_stage_assignment"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "judgement_config"
  ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "judgement_config_judge"
  ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "judgement_score"
  ALTER COLUMN "submitted_at" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "magic_link_token"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "participant"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "participant_otp"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "participant_session"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "payment"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "pending_invitation"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "programme"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "programme_assignment"
  ALTER COLUMN "assignedAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "programme_code_letter"
  ALTER COLUMN "issuedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "programme_code_letter_recipient"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "programme_notification"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "programme_reported_participant"
  ALTER COLUMN "reportedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "programme_reporting_session"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "programme_team_lead"
  ALTER COLUMN "appointedAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "result"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "schedule_entry"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "stage"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "stage_manager_assignment"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "stage_portal_credential"
  ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "stage_portal_session"
  ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "system_config"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "user"
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "user_login_event"
  ALTER COLUMN "loggedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "user_purchase_summary"
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- Add user.timezone (nullable — defaults to UTC; user picks in onboarding).
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "timezone" text;
UPDATE "user" SET "timezone" = 'UTC' WHERE "timezone" IS NULL;

-- Add festival.timezone (default UTC; organizer picks in festival setup).
ALTER TABLE "festival" ADD COLUMN IF NOT EXISTS "timezone" text DEFAULT 'UTC' NOT NULL;

COMMIT;

-- ─── Rollback (down migration, run manually if needed) ───────────────
-- BEGIN;
-- ALTER TABLE "user" DROP COLUMN IF EXISTS "timezone";
-- ALTER TABLE "festival" DROP COLUMN IF EXISTS "timezone";
-- DO $$
-- DECLARE r record;
-- BEGIN
--   FOR r IN
--     SELECT table_name, column_name
--     FROM information_schema.columns
--     WHERE table_schema = 'public' AND udt_name = 'timestamptz'
--   LOOP
--     EXECUTE format('ALTER TABLE %I ALTER COLUMN %I TYPE timestamp(3) USING (%I AT TIME ZONE %L)',
--       r.table_name, r.column_name, r.column_name, 'UTC');
--   END LOOP;
-- END$$;
-- COMMIT;