import type { Tier } from "@/core/types/app-enums";
import type { FeaturePath } from "@/features/plan-features/services/features";

/** Keys in TierFeatures that are boolean and can be toggled by Super Admin. */
export const PLAN_FEATURE_TOGGLE_KEYS = [
  "categories",
  "groups",
  "students",
  "programmes",
  "assignments",
  "chestNumbers",
  "results",
  "stageManagement",
  "schedule",
  "members",
  "roleBasedAccess",
  "studentImport",
  "studentBulkUpload",
  "programmeBulkUpload",
  "pdfExport",
  "excelExport",
  "emailNotifications",
  "whatsappSupport",
  "smsNotifications",
  "bulkNotifications",
  "advancedAnalytics",
  "customReports",
  "qrCodes",
  "autoCertificates",
  "customCertificateTemplates",
  "bulkCertificateGeneration",
  "publicLandingPage",
  "fullLandingPage",
  "landingPageBuilder",
  "gallery",
  "news",
  "customUrl",
  "customDomain",
  "logoUpload",
  "customColors",
  "whiteLabel",
  "apiAccess",
  "webhooks",
  "liveScoreboard",
  "liveResults",
  "multiFestivalManagement",
  "festivalSettings",
  "advancedSettings",
  "programmeAssignmentDeadline",
] as const satisfies readonly FeaturePath[];

/** Human-readable labels for the plan features matrix. */
export const PLAN_FEATURE_LABELS: Record<FeaturePath, string> = {
  categories: "Categories",
  groups: "Groups",
  students: "Students",
  viewStudentProfile: "Student Profile",
  publicStudentProfile: "Public Student Profile",
  programmes: "Programmes",
  assignments: "Assignments",
  chestNumbers: "Chest Numbers",
  results: "Results",
  stageManagement: "Stage Management",
  schedule: "Schedule",
  members: "Members",
  roleBasedAccess: "Role-based Access",
  studentImport: "Student Import",
  studentBulkUpload: "Student Bulk Upload",
  programmeBulkUpload: "Programme Bulk Upload",
  pdfExport: "PDF Export",
  excelExport: "Excel Export",
  emailNotifications: "Email Notifications",
  whatsappSupport: "WhatsApp Support",
  smsNotifications: "SMS Notifications",
  bulkNotifications: "Bulk Notifications",
  advancedAnalytics: "Advanced Analytics",
  customReports: "Custom Reports",
  templates: "Templates",
  qrCodes: "QR Codes",
  autoCertificates: "Auto Certificates",
  customCertificateTemplates: "Custom Certificate Templates",
  bulkCertificateGeneration: "Bulk Certificate Generation",
  publicLandingPage: "Public Landing Page",
  fullLandingPage: "Full Landing Page",
  landingPageBuilder: "Landing Page Builder",
  gallery: "Gallery",
  news: "News",
  customUrl: "Custom URL",
  customDomain: "Custom Domain",
  logoUpload: "Logo Upload",
  customColors: "Custom Colors",
  whiteLabel: "White Label",
  apiAccess: "API Access",
  webhooks: "Webhooks",
  liveScoreboard: "Live Scoreboard",
  liveResults: "Live Results",
  multiFestivalManagement: "Multi-festival Management",
  festivalSettings: "Festival Settings",
  advancedSettings: "Advanced Settings",
  programmeAssignmentDeadline: "Programme Assignment Deadline",
  supportLevel: "Support Level",
  supportResponseTime: "Support Response Time",
  postExpiryAccess: "Post-expiry Access",
  dataRetentionDays: "Data Retention Days",
};

export const PLANS: Tier[] = ["BASIC", "STANDARD", "PRO"];
