/**
 * Generate a PostgreSQL migration that converts every existing
 * `timestamp(3)` column to `timestamptz(3)`, treating the existing
 * values as UTC. Plus add `user.timezone` and `festival.timezone`.
 *
 * Reads the live DB schema via `information_schema` so the migration
 * is data-driven — no chance of missing a column or mismatched names.
 *
 * Run with: `npx tsx scripts/generate-tz-migration.ts`
 */

import "dotenv/config";
import { writeFileSync } from "node:fs";
import { Client } from "pg";

interface ColumnInfo {
  table_name: string;
  column_name: string;
  data_type: string;
  udt_name: string;
  column_default: string | null;
  is_nullable: string;
  datetime_precision: number | null;
}

async function main() {
  const url =
    process.env.DATABASE_URL_UNPOOLED ||
    process.env.DATABASE_URL ||
    "postgresql://postgres:postgres@localhost:5433/greenroom?sslmode=disable";
  const client = new Client({ connectionString: url });
  await client.connect();

  // 1. Find every `timestamp` (without TZ) column currently in the DB.
  const { rows } = await client.query<ColumnInfo>(`
    SELECT
      c.table_name,
      c.column_name,
      c.data_type,
      c.udt_name,
      c.column_default,
      c.is_nullable,
      c.datetime_precision
    FROM information_schema.columns c
    JOIN information_schema.tables t
      ON t.table_schema = c.table_schema AND t.table_name = c.table_name
    WHERE c.table_schema = 'public'
      AND t.table_type = 'BASE TABLE'
      AND c.udt_name = 'timestamp'
    ORDER BY c.table_name, c.column_name;
  `);

  console.log(`Found ${rows.length} timestamp columns to convert.`);

  // Group by table so we can emit a single ALTER TABLE per table.
  const byTable = new Map<string, ColumnInfo[]>();
  for (const row of rows) {
    const arr = byTable.get(row.table_name) ?? [];
    arr.push(row);
    byTable.set(row.table_name, arr);
  }

  const lines: string[] = [];
  lines.push(
    `-- Migration: convert every timestamp(3) column to timestamptz(3) (UTC).`,
    `-- Generated by scripts/generate-tz-migration.ts`,
    `-- Backfill rule: existing values are interpreted as UTC (the historical`,
    `-- convention — every prior writer used .toISOString() / toISOString UTC).`,
    ``,
    `BEGIN;`,
    ``,
  );

  // 2. ALTER TABLE statements — one per table.
  for (const [tableName, columns] of byTable) {
    const alters = columns.map((col) => {
      const newType = "TIMESTAMPTZ(3)";
      // Cast: read the column's text representation, parse as UTC, store
      // as timestamptz. This handles both '2026-08-15 09:00:00.000' and
      // '2026-08-15T09:00:00.000Z' shapes because `text::timestamptz`
      // accepts both.
      const using = `USING (${quoteIdent(col.column_name)}::text)::timestamptz`;
      return `  ALTER COLUMN ${quoteIdent(col.column_name)} TYPE ${newType} ${using}`;
    });
    lines.push(
      `ALTER TABLE ${quoteIdent(tableName)}`,
      `${alters.join(",\n")};`,
      ``,
    );
  }

  // 3. Re-affirm the DEFAULT CURRENT_TIMESTAMP where it was set, because
  //    changing the column type drops the default in some PG versions.
  for (const [tableName, columns] of byTable) {
    const defaulted = columns.filter((c) =>
      c.column_default?.toLowerCase().includes("current_timestamp"),
    );
    if (defaulted.length === 0) continue;
    lines.push(
      `ALTER TABLE ${quoteIdent(tableName)}`,
      defaulted
        .map(
          (c) =>
            `  ALTER COLUMN ${quoteIdent(c.column_name)} SET DEFAULT CURRENT_TIMESTAMP`,
        )
        .join(",\n") + `;`,
      ``,
    );
  }

  // 4. Add the new timezone columns.
  lines.push(
    `-- Add user.timezone (nullable — defaults to UTC; user picks in onboarding).`,
    `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "timezone" text;`,
    `UPDATE "user" SET "timezone" = 'UTC' WHERE "timezone" IS NULL;`,
    ``,
    `-- Add festival.timezone (default UTC; organizer picks in festival setup).`,
    `ALTER TABLE "festival" ADD COLUMN IF NOT EXISTS "timezone" text DEFAULT 'UTC' NOT NULL;`,
    ``,
    `COMMIT;`,
    ``,
    `-- ─── Rollback (down migration, run manually if needed) ───────────────`,
    `-- BEGIN;`,
    `-- ALTER TABLE "user" DROP COLUMN IF EXISTS "timezone";`,
    `-- ALTER TABLE "festival" DROP COLUMN IF EXISTS "timezone";`,
    `-- DO $$`,
    `-- DECLARE r record;`,
    `-- BEGIN`,
    `--   FOR r IN`,
    `--     SELECT table_name, column_name`,
    `--     FROM information_schema.columns`,
    `--     WHERE table_schema = 'public' AND udt_name = 'timestamptz'`,
    `--   LOOP`,
    `--     EXECUTE format('ALTER TABLE %I ALTER COLUMN %I TYPE timestamp(3) USING (%I AT TIME ZONE %L)',`,
    `--       r.table_name, r.column_name, r.column_name, 'UTC');`,
    `--   END LOOP;`,
    `-- END$$;`,
    `-- COMMIT;`,
  );

  const sql = lines.join("\n");
  const outPath = "drizzle/0027_convert_to_timestamptz_and_add_timezones.sql";
  writeFileSync(outPath, sql, "utf8");
  console.log(
    `Wrote ${outPath} (${rows.length} columns across ${byTable.size} tables).`,
  );

  await client.end();
}

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
